# Assignment 6: Collateralised FX and Interest-Rate Products

**Aditya Amit Shah | as22008**  
FRE-GT-9743 - Special Topics: Models to Markets

The written solution answers all three questions in the assignment PDF. The computational section completes the six assigned library methods and retains the supplied examples and inputs. All code cells below are executed with saved output.

## Written solution - 1. Valuation formula

Let $t$ be the valuation date and $T$ the common settlement date. Write $E=\mathrm{EUR}$, $U=\mathrm{USD}$ and $G=\mathrm{GBP}$. Define:

- $S_t$: spot USD per EUR; $X_t$: spot USD per GBP.
- $N$: EUR notional; $K$: contracted USD per EUR.
- $P^{i\mid k}(t,T)$: the value **in currency $i$** of one unit of $i$ paid at $T$, when the trade is collateralised in currency $k$.

Consider the position receiving $N$ EUR and paying $NK$ USD at $T$. Assume full, symmetric, continuously adjusted cash collateral in GBP, remunerated at SONIA, with zero threshold and minimum transfer amount, and no default, collateral optionality, or transaction costs. The sign reverses for the opposite position. All discount factors below refer to the same $(t,T)$.

The EUR receipt has EUR PV $NP^{E\mid G}$, or USD PV $NS_tP^{E\mid G}$. The USD payment has USD PV $NKP^{U\mid G}$. By linearity,

$$\boxed{V_U^{G}(t)=N\left[S_tP^{E\mid G}(t,T)-KP^{U\mid G}(t,T)\right].}$$

Equivalently, directly in the currency-GBP pricing measure,

$$V_U^{G}(t)=NX_t\,\mathbb E_t^{Q_G}\!\left[\exp\!\left(-\int_t^T c_G(u)\,du\right)\frac{S_T-K}{X_T}\right],$$

where $Q_G$ is the currency-GBP risk-neutral measure and $c_G$ is the GBP collateral remuneration rate (SONIA). The payoff must first be converted into GBP at the **terminal** FX rate. This explains why directly applying the SONIA discount factor to a USD payoff is generally incorrect. Reporting in GBP gives $V_G^{G}=V_U^{G}/X_t$; reporting currency does not change the fair strike.

## Written solution - 2. Fair forward strike

Set the inception PV to zero and solve for the strike:

$$\boxed{K_G^*(t,T)=S_t\frac{P^{E\mid G}(t,T)}{P^{U\mid G}(t,T)}.}$$

Consequently,

$$V_U^{G}(t)=NP^{U\mid G}(t,T)\left[K_G^*(t,T)-K\right].$$

This has the expected sign: for receive-EUR/pay-USD, a contracted strike below the current fair strike gives a positive value. At $T$, both discount factors equal one and the formula reduces to $N(S_T-K)$. A forward-starting FX trade with separate near and far exchanges would require both exchanges; the formula here is for the single settlement specified in the question.

## Written solution - 3. Are the five discount factors sufficient?

**The five curves alone are not sufficient without a collateral-switch assumption. They are sufficient in a deterministic, consistent collateral-basis curve framework, provided spot FX is also known.** The assignment does not define the bracket notation, so the convention must be stated.

First interpret $df^{[i,U]}$ as the **full discount factor** $P^{i\mid U}$. Then the supplied curves are

$$D_G=df^{\mathrm{SONIA}}=P^{G\mid G},\quad D_E=df^{\mathrm{EuroSTR}}=P^{E\mid E},\quad D_U=df^{\mathrm{SOFR}}=P^{U\mid U},$$
$$A_G=df^{[G,U]}=P^{G\mid U},\qquad A_E=df^{[E,U]}=P^{E\mid U}.$$

**Deterministic collateral-basis construction.** Let $r_i$ be the formal currency-$i$ financing/risk-free rate, $c_i$ its collateral remuneration, and $y_i=r_i-c_i$ the collateral funding benefit, and assume the switch spread $b_{U,G}=y_U-y_G$ is deterministic over $[t,T]$. The effective short rate for currency $i$ under collateral $k$ is $r_i-y_k$. Switching USD collateral to GBP therefore adds the same $b_{U,G}$ for every payout currency:

$$P^{i\mid G}=L_{G\leftarrow U}P^{i\mid U},\qquad L_{G\leftarrow U}=\exp\!\left(-\int_t^T b_{U,G}(u)\,du\right).$$

Taking $i=G$ identifies the switch factor from supplied curves:

$$L_{G\leftarrow U}=\frac{D_G}{A_G},\qquad
\boxed{P^{U\mid G}=\frac{D_GD_U}{A_G},\quad P^{E\mid G}=\frac{D_GA_E}{A_G}.}$$

Hence,

$$\boxed{K_G^*=S_t\frac{A_E}{D_U},\qquad V_U^G=N\frac{D_G}{A_G}\left(S_tA_E-KD_U\right).}$$

The common switch factor cancels from the fair strike, but scales an off-market PV. EuroSTR is redundant for this particular calculation because $A_E$ already includes the EUR-versus-USD collateral adjustment; it can be used to extract that adjustment as $A_E/D_E$. SONIA alone cannot discount both currency legs, and using only EuroSTR/SOFR omits cross-currency basis.

**If the bracket curves are basis-only factors instead.** Define $B_{i,U}=P^{i\mid U}/D_i$. If the supplied $df^{[G,U]}$ and $df^{[E,U]}$ mean $B_{G,U}$ and $B_{E,U}$, substitute $A_G=D_GB_{G,U}$ and $A_E=D_EB_{E,U}$. The same construction becomes

$$P^{U\mid G}=\frac{D_U}{B_{G,U}},\qquad P^{E\mid G}=\frac{D_EB_{E,U}}{B_{G,U}},$$
$$K_G^*=S_t\frac{D_EB_{E,U}}{D_U},\qquad V_U^G=\frac{N}{B_{G,U}}\left(S_tD_EB_{E,U}-KD_U\right).$$

**General stochastic qualification.** Without the deterministic/separable switch assumption, the effective discount factor is an expectation of an exponential involving rates and funding spreads. A stochastic switch factor cannot be taken outside that expectation. USD-collateralised curves do not determine the GBP-collateralised EUR and USD discount factors; their joint FX/rate/basis dynamics or the required GBP-collateral curves must also be supplied. FX-forward triangulation uses a common collateral currency and does not itself justify switching collateral. Thus the cancellation above is a consequence of the stated curve model, not a general consequence of no-arbitrage.

The general collateral pricing relation and collateral-specific FX forward are consistent with Fujii and Takahashi, *A General Framework for the Benchmark Pricing in a Fully Collateralized Market*, Theorem 2.1 and Section 5.1, [arXiv:1508.06339](https://arxiv.org/abs/1508.06339). The deterministic switch identities above follow by factoring out the assumed deterministic spread.

### Numerical check of the deterministic construction

The following one-year example is **illustrative**, not additional assignment market data. It checks the full-curve and basis-factor representations, zero PV at the fair strike, and the sign for a receive-EUR forward below the fair strike.

In [1]:
import numpy as np
import pandas as pd
from IPython.display import display

fx_spot, fx_notional = 1.10, 1_000_000.0
D_G, D_E, D_U = np.exp(-0.035), np.exp(-0.020), np.exp(-0.040)
A_G, A_E = np.exp(-0.037), np.exp(-0.023)
switch_factor = D_G / A_G
P_U_G, P_E_G = switch_factor * D_U, switch_factor * A_E
fair_fx_strike = fx_spot * P_E_G / P_U_G
fx_strike = 1.11
fx_pv = fx_notional * (fx_spot * P_E_G - fx_strike * P_U_G)
B_G_U, B_E_U = A_G / D_G, A_E / D_E
np.testing.assert_allclose([P_U_G, P_E_G], [D_U/B_G_U, D_E*B_E_U/B_G_U])
np.testing.assert_allclose(fair_fx_strike, fx_spot*A_E/D_U)
np.testing.assert_allclose(fx_notional*(fx_spot*P_E_G-fair_fx_strike*P_U_G), 0.0, atol=1e-8)
np.testing.assert_allclose(fx_pv, fx_notional*P_U_G*(fair_fx_strike-fx_strike), atol=1e-8)
assert fx_pv > 0.0
display(pd.DataFrame({"Quantity": ["GBP collateral switch factor", "USD DF under GBP", "EUR DF under GBP", "Fair USD per EUR strike", "PV at K=1.11 (USD)"],
                      "Value": [switch_factor, P_U_G, P_E_G, fair_fx_strike, fx_pv]}))

                       Quantity        Value
0  GBP collateral switch factor     1.002002
1              USD DF under GBP     0.962713
2              EUR DF under GBP     0.979219
3       Fair USD per EUR strike     1.118860
4            PV at K=1.11 (USD)  8529.496637

## Computational solution: Interest-Rate Products and Valuation

All six assigned library methods are completed:

| File | Method | Implementation |
|---|---|---|
| `product/linear_products.py` | `ProductRFRSwap.__init__` | Fixed and overnight legs, each with its own accrual period. |
| `product/linear_products.py` | `ProductOvernightIndexBasisSwap.__init__` | Two overnight legs; the quoted spread is applied only to leg 1. |
| `product/product_factory.py` | `create_rfr_swap` | Convention fields, trade quote, and spot/forward/explicit-date rules. |
| `product/product_factory.py` | `create_overnight_index_basis_swap` | Both index conventions, frequencies, and the quoted spread. |
| `yield_curve/valuation_engine.py` | `ValuationEngineProductRfrSwap.calculate_value` | Signed fixed and floating PV/cash. |
| `yield_curve/valuation_engine.py` | `ValuationEngineProductOvernightIndexBasisSwap.calculate_value` | Signed leg-1 index, leg-1 spread, and leg-2 index PV/cash. |

The supplied FRA implementation and stream engines are reused. Each floating leg projects with its own index curve; all payments discount with the funding curve. Inputs and the starter's computational examples are retained below. Restart the kernel and run all cells after editing the library. The starter recommends Python 3.11 and `requirements.txt`.

In [2]:
import numpy as np
import pandas as pd
from IPython.display import display

from fixedincomelib import (
    qfCreateData1D, qfCreateDataCollection,
    qfCreateBuildMethod, qfCreateModelBuildMethodCollection, qfCreateModel,
    qfCreateProductInterestRateStream, qfCreateProductFRA,
    qfCreateProductRFRSwap, qfCreateProductOvernightIndexBasisSwap,
    qfCreateProductFromDataConvention, qfDisplayProduct,
    qfCreateValuationParameters, qfCreateValuationParametersCollection,
    qfCreateValueReport, qfCreateCashflowsReport, qfInsertTermRateFixing,
)
from fixedincomelib.date import Date
from fixedincomelib.market.registries import DataConventionRegistry
from fixedincomelib.valuation import ValuationRequest
from fixedincomelib.yield_curve.valuation_engine import (
    ValuationEngineInterestRateStream, ValuationEngineProductFra,
    ValuationEngineProductRfrSwap, ValuationEngineProductOvernightIndexBasisSwap,
)

np.set_printoptions(precision=6, suppress=True)
pd.options.display.float_format = "{:,.6f}".format
pd.options.display.max_colwidth = None

## 1. Input data

Rates are annual decimals: `0.04 = 4%`, `0.001 = 10 bp`. These are synthetic teaching inputs.
SOFR and Fed Funds have separate projection curves. The funding component adds an IFR spread
on top of SOFR, as in HW5. Edit the inputs here and rerun the following cells.

In [3]:
VALUE_DATE = "2026-01-02"
EFFECTIVE_DATE = "2026-04-02"
FRA_END_DATE = "2026-07-02"
SWAP_END_DATE = "2027-04-02"
FUNDING_INDEX = "SOFR-1B-FLAT"
NOTIONAL = 1_000_000
FIXED_RATE = 0.04
BASIS_SPREAD = 0.001
BASIS_CONVENTION = "USD-FF-3M-OVER-USD-SOFR-OIS-3M"

sofr_quotes = pd.DataFrame(
    {"values": [0.03, 0.04, 0.05]},
    index=pd.Index(["2026-04-02", "2027-01-04", "2028-01-03"], name="Node date"),
)
ff_quotes = pd.DataFrame(
    {"values": [0.028, 0.037]},
    index=pd.Index(["2026-07-02", "2028-01-03"], name="Node date"),
)
funding_quotes = pd.DataFrame(
    {"values": [0.0, 0.001]},
    index=pd.Index(["2026-07-02", "2028-01-03"], name="Node date"),
)

display(sofr_quotes.rename(columns={"values": "SOFR-1B IFR"}))
display(ff_quotes.rename(columns={"values": "FF-1B IFR"}))
display(funding_quotes.rename(columns={"values": "Funding IFR spread"}))

            SOFR-1B IFR
Node date
2026-04-02     0.030000
2027-01-04     0.040000
2028-01-03     0.050000

            FF-1B IFR
Node date
2026-07-02   0.028000
2028-01-03   0.037000

            Funding IFR spread
Node date
2026-07-02            0.000000
2028-01-03            0.001000

## 2. Data and build methods

Create the IFR datasets and build methods, with SOFR first, Fed Funds second and funding third.
The model construction copies these IFR inputs into state variables, as in HW5.

In [4]:
sofr_data = qfCreateData1D("INSTANTANEOUS FORWARD RATE", "SOFR-1B-IFR", sofr_quotes)
ff_data = qfCreateData1D("INSTANTANEOUS FORWARD RATE", "FF-1B-IFR", ff_quotes)
funding_data = qfCreateData1D(
    "INSTANTANEOUS FORWARD RATE", "SOFR-1B-FUNDING-IFR", funding_quotes,
)
data_collection = qfCreateDataCollection([sofr_data, ff_data, funding_data])
display(data_collection.display())

  Data Shape                   Data Type      Data Convention
0     DATA1D  INSTANTANEOUS FORWARD RATE          SOFR-1B-IFR
1     DATA1D  INSTANTANEOUS FORWARD RATE            FF-1B-IFR
2     DATA1D  INSTANTANEOUS FORWARD RATE  SOFR-1B-FUNDING-IFR

In [5]:
sofr_method = qfCreateBuildMethod("YIELD_CURVE_INDEX", {
    "TARGET": "SOFR-1B", "INSTANTANEOUS FORWARD RATE": "SOFR-1B-IFR",
})
ff_method = qfCreateBuildMethod("YIELD_CURVE_INDEX", {
    "TARGET": "FF-1B", "INSTANTANEOUS FORWARD RATE": "FF-1B-IFR",
})
funding_method = qfCreateBuildMethod("YIELD_CURVE_FUNDING", {
    "TARGET": FUNDING_INDEX, "REFERENCE INDEX": "SOFR-1B",
    "INSTANTANEOUS FORWARD RATE": "SOFR-1B-FUNDING-IFR",
})
build_methods = qfCreateModelBuildMethodCollection([sofr_method, ff_method, funding_method])

## 3. Build the model

The projection index selects the curve used to estimate a floating coupon.
`FundingIndexParameter` selects the curve used to discount both legs on their payment dates.

In [6]:
model = qfCreateModel(VALUE_DATE, "YIELD_CURVE", data_collection, build_methods)
funding_parameter = qfCreateValuationParameters(
    "FUNDING INDEX PARAMETER", {"FUNDING INDEX": FUNDING_INDEX},
)
parameters = qfCreateValuationParametersCollection([funding_parameter])

print("Component sizes:", model.num_sub_components)
print("Component order:", model.component_indices)
print("SOFR DF:", model.discount_factor("SOFR-1B", Date(FRA_END_DATE)))
print("Funding DF:", model.discount_factor(FUNDING_INDEX, Date(FRA_END_DATE)))

Component sizes: [3, 2, 2]
Component order: {'SOFRON Actual/360': 0, 'FedFundsON Actual/360': 1, 'SOFR-1B-FLAT': 2}
SOFR DF: 0.9827801233868858
Funding DF: 0.9827801233868858

## 4. Interest-rate streams

`ProductInterestRateStream` is the supplied leg helper. A fixed coupon pays $N K \alpha$;
an overnight coupon pays $N\alpha(R+s)$, with spread added outside daily compounding.
The existing fixed-accrued cashflow still represents $N\alpha$; the stream applies $K$ once.

`ProductInterestRateStream` and `ValuationEngineInterestRateStream` are supplied in full.
Use `accrual_period=None` for a single coupon and `is_on_index=False` for a term-rate coupon.

In [7]:
fixed_stream = qfCreateProductInterestRateStream(
    EFFECTIVE_DATE, SWAP_END_DATE, "1Y", NOTIONAL, "USD", "ACT/360",
    fixed_rate=FIXED_RATE, payment_offset="2D",
)
overnight_stream = qfCreateProductInterestRateStream(
    EFFECTIVE_DATE, SWAP_END_DATE, "1Y", NOTIONAL, "USD", "ACT/360",
    holiday_convention="SOFR", float_index="SOFR-1B", payment_offset="2D",
)

display(qfDisplayProduct(fixed_stream))
display(qfCreateCashflowsReport(model, fixed_stream, parameters).display())
display(qfCreateCashflowsReport(model, overnight_stream, parameters).display())

                   Name                         Value
0          Product Type  PRODUCT_INTEREST_RATE_STREAM
1              Notional                       1000000
2              Currency                           USD
3         Long Or Short                          LONG
4        Effective Date                    2026-04-02
5      Termination Date                    2027-04-02
6     Last Payment Date                    2027-04-06
7   Number of Cashflows                             1
8            Fixed Rate                      0.040000
9        Floating Index                          None
10      Overnight Index                          None

,Leg,Currency,Accrual Start,Accrual End,Payment Date,Notional,Accrual,Rate,Spread,Cashflow,Discount Factor,PV
0,Stream,USD,2026-04-02,2027-04-02,2027-04-06,1000000,1.013889,0.040000,0.000000,"40,555.555556",0.950167,"38,534.539463"

,Leg,Currency,Accrual Start,Accrual End,Payment Date,Notional,Accrual,Rate,Spread,Cashflow,Discount Factor,PV
0,Stream,USD,2026-04-02,2027-04-02,2027-04-06,1000000,1.013889,0.042730,0.000000,"43,323.153601",0.950167,"41,164.219038"

In [8]:
stream_engine = ValuationEngineInterestRateStream(
    model, parameters, overnight_stream, ValuationRequest.PV,
)
stream_engine.calculate_value()
print("Floating stream PV:", stream_engine.value)
print("Cash today:", stream_engine.cash)

Floating stream PV: 41164.21903793787
Cash today: 0.0

## 5. FRA

The teaching FRA fixes the whole-period simple rate at $T_s$ and settles at $T_e$.
Before fixing, use the SOFR projection curve to calculate
$F=(P_p(t,T_s)/P_p(t,T_e)-1)/\tau$.
For receive-fixed, $PV=N\tau(K-F)D_f(t,T_e)$. `pay` reverses the sign.
The projection curve identifies a teaching term rate; its fixing is stored separately from daily SOFR fixings.

The FRA is supplied in full. Read `ProductFRA.__init__`, `ProductFactory.create_fra`,
and `ValuationEngineProductFra.calculate_value` to see how product construction,
convention-driven creation, and leg valuation fit together. Use these implementations
as the starting point for the two swap products.

In [9]:
fra = qfCreateProductFRA(
    EFFECTIVE_DATE, FRA_END_DATE, "SOFR-1B", FIXED_RATE, "receive", NOTIONAL,
    accrual_basis="ACT/360",
)
display(qfDisplayProduct(fra))
display(qfCreateCashflowsReport(model, fra, parameters).display())

                    Name        Value
0           Product Type  PRODUCT_FRA
1               Notional      1000000
2               Currency          USD
3          Long Or Short         LONG
4         Effective Date   2026-04-02
5       Termination Date   2026-07-02
6            Fixing Date   2026-04-02
7           Payment Date   2026-07-02
8       Projection Index      SOFR-1B
9             Fixed Rate     0.040000
10  Pay Or Receive Fixed      RECEIVE
11         Accrual Basis      ACT/360

,Leg,Currency,Accrual Start,Accrual End,Payment Date,Notional,Accrual,Rate,Spread,Cashflow,Discount Factor,PV
0,Fixed,USD,2026-04-02,2026-07-02,2026-07-02,"1,000,000.000000",0.252778,0.040000,0.000000,"10,111.111111",0.982780,"9,936.999025"
1,Floating,USD,2026-04-02,2026-07-02,2026-07-02,"-1,000,000.000000",0.252778,0.039649,0.000000,"-10,022.494856",0.982780,"-9,849.908731"

In [10]:
df_start = model.discount_factor("SOFR-1B", fra.effective_date)
df_end = model.discount_factor("SOFR-1B", fra.termination_date)
forward_rate = (df_start / df_end - 1.0) / fra.accrued
expected_fra_pv = (
    NOTIONAL * fra.accrued * (FIXED_RATE - forward_rate)
    * model.discount_factor(FUNDING_INDEX, fra.payment_date)
)
fra_engine = ValuationEngineProductFra(model, parameters, fra, ValuationRequest.PV)
fra_engine.calculate_value()
print("Projected term rate:", forward_rate)
print("FRA PV / formula:", fra_engine.value, expected_fra_pv)
np.testing.assert_allclose(fra_engine.value, expected_fra_pv, atol=1e-8)

Projected term rate: 0.03964943019925975
FRA PV / formula: 87.09029420688239 87.09029420688128

Once $T_s$ is reached, supply the observed term fixing and discount the known payment.
The following fixing is synthetic.

In [11]:
fixing_model = qfCreateModel(EFFECTIVE_DATE, "YIELD_CURVE", data_collection, build_methods)
observed_term_rate = 0.045
qfInsertTermRateFixing("SOFR-1B", EFFECTIVE_DATE, FRA_END_DATE, "ACT/360", observed_term_rate)
fixed_fra_pv = qfCreateValueReport(fixing_model, fra, parameters, "PV")[0][1]
known_amount = NOTIONAL * fra.accrued * (FIXED_RATE - observed_term_rate)
print("Known amount at Te:", known_amount)
print("PV on Ts:", fixed_fra_pv)
np.testing.assert_allclose(
    fixed_fra_pv, known_amount * fixing_model.discount_factor(FUNDING_INDEX, fra.payment_date),
    atol=1e-8,
)

Known amount at Te: -1263.8888888888882
PV on Ts: -1251.3472673390097

## 6. Vanilla RFR swap

The template's vanilla swap is fixed versus compounded overnight interest.
`receive` means receive the fixed leg and pay the floating leg.
Each leg uses the stream helper; the swap engine combines their PV and cash.
Unlike the FRA term coupon, an overnight coupon accumulates fixings throughout its accrual period.

`ProductRFRSwap.__init__` constructs `fixed_leg_` and `floating_leg_` through `InterestRateStream`. Each leg preserves its own accrual period and the payment conventions; the floating leg uses the overnight index, compounding method, and spread. `ValuationEngineProductRfrSwap.calculate_value` combines the two leg engines using the supplied pay/receive signs for both PV and cash.

In [12]:
swap = qfCreateProductRFRSwap(
    effective_date=EFFECTIVE_DATE, term_or_termination_date=SWAP_END_DATE,
    payment_off_set="2D", on_index="SOFR-1B", fixed_rate=FIXED_RATE,
    pay_or_rec="receive", notional=NOTIONAL,
    accrual_period="1Y", accrual_basis="ACT/360",
    floating_leg_accrual_period="1Y",
)
display(qfDisplayProduct(swap))
display(qfCreateCashflowsReport(model, swap, parameters).display())

                       Name             Value
0              Product Type  PRODUCT_RFR_SWAP
1                  Notional           1000000
2                  Currency               USD
3             Long Or Short              LONG
4            Effective Date        2026-04-02
5          Termination Date        2027-04-02
6         Last Payment Date        2027-04-06
7                  ON Index           SOFR-1B
8                Fixed Rate          0.040000
9                    Spread          0.000000
10     Pay Or Receive Fixed           RECEIVE
11     Fixed Accrual Period                1Y
12  Floating Accrual Period                1Y
13       Compounding Method          COMPOUND

,Leg,Currency,Accrual Start,Accrual End,Payment Date,Notional,Accrual,Rate,Spread,Cashflow,Discount Factor,PV
0,Fixed,USD,2026-04-02,2027-04-02,2027-04-06,"1,000,000.000000",1.013889,0.040000,0.000000,"40,555.555556",0.950167,"38,534.539463"
1,Floating,USD,2026-04-02,2027-04-02,2027-04-06,"-1,000,000.000000",1.013889,0.042730,0.000000,"-43,323.153601",0.950167,"-41,164.219038"

In [13]:
swap_engine = ValuationEngineProductRfrSwap(model, parameters, swap, ValuationRequest.PV)
swap_engine.calculate_value()
fixed_pv = qfCreateValueReport(model, swap.fixed_leg, parameters, "PV")[0][1]
floating_pv = qfCreateValueReport(model, swap.floating_leg, parameters, "PV")[0][1]
print("Fixed / floating PV:", fixed_pv, floating_pv)
print("Swap PV:", swap_engine.value)
np.testing.assert_allclose(swap_engine.value, fixed_pv - floating_pv, atol=1e-8)

Fixed / floating PV: 38534.53946314968 41164.21903793787
Swap PV: -2629.6795747881915

## 7. Overnight index basis swap

The template convention specifies leg 1 as SOFR plus spread and leg 2 as Fed Funds.
`receive` means receive leg 1 and pay leg 2. Each index uses its own projection curve;
both legs use the same USD funding curve. The convention's original template name is retained.

`ProductOvernightIndexBasisSwap.__init__` creates both overnight streams with their respective indices and accrual periods, applying `spread_` only to leg 1. The valuation engine uses `_legs()` to sum the signed leg-1 index, leg-1 spread, and leg-2 index PVs and cash. It resets both totals before every calculation.

In [14]:
basis_swap = qfCreateProductOvernightIndexBasisSwap(
    effective_date=EFFECTIVE_DATE, term_or_termination_date=SWAP_END_DATE,
    payment_off_set="2D", on_index_leg_1="SOFR-1B", on_index_leg_2="FF-1B",
    spread_over_leg_1=BASIS_SPREAD, pay_or_rec_leg_1="receive", notional=NOTIONAL,
    accrual_period_1="3M", accrual_period_2="3M", accrual_basis="ACT/360",
)
display(qfDisplayProduct(basis_swap))
display(qfCreateCashflowsReport(model, basis_swap, parameters).display())

                    Name                               Value
0           Product Type  PRODUCT_OVERNIGHT_INDEX_BASIS_SWAP
1               Notional                             1000000
2               Currency                                 USD
3          Long Or Short                                LONG
4         Effective Date                          2026-04-02
5       Termination Date                          2027-04-02
6      Last Payment Date                          2027-04-06
7         ON Index Leg 1                             SOFR-1B
8         ON Index Leg 2                               FF-1B
9      Spread Over Leg 1                            0.001000
10  Pay Or Receive Leg 1                             RECEIVE
11  Accrual Period Leg 1                                  3M
12  Accrual Period Leg 2                                  3M
13    Compounding Method                            COMPOUND

,Leg,Currency,Accrual Start,Accrual End,Payment Date,Notional,Accrual,Rate,Spread,Cashflow,Discount Factor,PV
0,Leg 1 index,USD,2026-04-02,2026-07-02,2026-07-07,"1,000,000.000000",0.252778,0.039649,0.000000,"10,022.494856",0.982228,"9,844.378144"
1,Leg 1 index,USD,2026-07-02,2026-10-02,2026-10-06,"1,000,000.000000",0.255556,0.039652,0.000000,"10,133.188318",0.972239,"9,851.882801"
2,Leg 1 index,USD,2026-10-02,2027-01-04,2027-01-06,"1,000,000.000000",0.261111,0.039656,0.000000,"10,354.611638",0.962191,"9,963.112508"
3,Leg 1 index,USD,2027-01-04,2027-04-02,2027-04-06,"1,000,000.000000",0.244444,0.049614,0.000000,"12,127.746401",0.950167,"11,523.381098"
4,Leg 1 spread,USD,2026-04-02,2026-07-02,2026-07-07,"1,000,000.000000",0.252778,0.001000,0.000000,252.777778,0.982228,248.285488
5,Leg 1 spread,USD,2026-07-02,2026-10-02,2026-10-06,"1,000,000.000000",0.255556,0.001000,0.000000,255.555556,0.972239,248.461126
6,Leg 1 spread,USD,2026-10-02,2027-01-04,2027-01-06,"1,000,000.000000",0.261111,0.001000,0.000000,261.111111,0.962191,251.238720
7,Leg 1 spread,USD,2027-01-04,2027-04-02,2027-04-06,"1,000,000.000000",0.244444,0.001000,0.000000,244.444444,0.950167,232.262978
8,Leg 2 index,USD,2026-04-02,2026-07-02,2026-07-07,"-1,000,000.000000",0.252778,0.027713,0.000000,"-7,005.244652",0.982228,"-6,880.749588"
9,Leg 2 index,USD,2026-07-02,2026-10-02,2026-10-06,"-1,000,000.000000",0.255556,0.036664,0.000000,"-9,369.650295",0.972239,"-9,109.541212"
10,Leg 2 index,USD,2026-10-02,2027-01-04,2027-01-06,"-1,000,000.000000",0.261111,0.036668,0.000000,"-9,574.310367",0.962191,"-9,212.313770"
11,Leg 2 index,USD,2027-01-04,2027-04-02,2027-04-06,"-1,000,000.000000",0.244444,0.036656,0.000000,"-8,960.454608",0.950167,"-8,513.925823"

In [15]:
basis_engine = ValuationEngineProductOvernightIndexBasisSwap(
    model, parameters, basis_swap, ValuationRequest.PV,
)
basis_engine.calculate_value()
leg_1_pv = qfCreateValueReport(model, basis_swap.floating_leg_1, parameters, "PV")[0][1]
leg_2_pv = qfCreateValueReport(model, basis_swap.floating_leg_2, parameters, "PV")[0][1]
print("Leg 1 / leg 2 PV:", leg_1_pv, leg_2_pv)
print("Basis swap PV:", basis_engine.value)
np.testing.assert_allclose(basis_engine.value, leg_1_pv - leg_2_pv, atol=1e-8)

Leg 1 / leg 2 PV: 42163.002863421294 33716.530392254324
Basis swap PV: 8446.47247116697

## 8. Product factory

`qfCreateProductFromDataConvention` looks up the convention and dispatches to its registered builder.
The quote is the fixed rate for FRA/swap and the spread over leg 1 for the basis swap.

| Product | `axis1` | Meaning |
|---|---|---|
| FRA | `3Mx6M` | Start in 3 months, end in 6 months, both from `value_date` |
| FRA | `2026-04-02x2026-07-02` | Explicit start and end |
| Swap / basis swap | `3Mx1Y` | Start in 3 months, then run for 1 year |
| Swap / basis swap | `1Y` | Spot-starting, run for 1 year |

`ProductFactory.create_fra` is the worked builder example. The common dispatcher
`create_product_from_data_convention`, tokenizer, and registrations are supplied.
The two completed builders in `fixedincomelib/product/product_factory.py` map convention fields into their product constructors:

- `create_rfr_swap`: read the swap convention and create fixed and overnight legs
  through `ProductRFRSwap`; the quote is the fixed rate.
- `create_overnight_index_basis_swap`: read both indices and their accrual periods,
  then create `ProductOvernightIndexBasisSwap`; the quote is the spread on leg 1.

The builders follow the FRA convention mapping and use the swap date rules in the table above.

In [16]:
display(DataConventionRegistry().get("USD-SOFR-FRA").display())
display(DataConventionRegistry().get("USD-SOFR-OIS").display())

                      Name    Value
0                    INDEX  SOFR-1B
1            ACCRUAL_BASIS  ACT/360
2  BUSINESS_DAY_CONVENTION        F
3       HOLIDAY_CONVENTION     USGS
4            FIXING_OFFSET       0D
5           PAYMENT_OFFSET       0D

                              Name     Value
0                            INDEX   SOFR-1B
1                    ACCRUAL_BASIS   ACT/360
2                   ACCRUAL_PERIOD        1Y
3                   PAYMENT_OFFSET        2D
4  PAYMENT_BUSINESS_DAY_CONVENTION         F
5       PAYMENT_HOLIDAY_CONVENTION      USGS
6               COMPOUNDING_METHOD  COMPOUND

In [17]:
factory_fra = qfCreateProductFromDataConvention(
    VALUE_DATE, "USD-SOFR-FRA", f"{EFFECTIVE_DATE}x{FRA_END_DATE}", FIXED_RATE,
    notional=NOTIONAL, pay_or_rec="receive",
)
factory_swap = qfCreateProductFromDataConvention(
    VALUE_DATE, "USD-SOFR-OIS", f"{EFFECTIVE_DATE}x{SWAP_END_DATE}", FIXED_RATE,
    notional=NOTIONAL, pay_or_rec="receive",
)
factory_basis = qfCreateProductFromDataConvention(
    VALUE_DATE, BASIS_CONVENTION, f"{EFFECTIVE_DATE}x{SWAP_END_DATE}", BASIS_SPREAD,
    notional=NOTIONAL, pay_or_rec="receive",
)

for direct, created in [(fra, factory_fra), (swap, factory_swap), (basis_swap, factory_basis)]:
    assert direct.serialize() == created.serialize()
    print(created.product_type, qfCreateValueReport(model, created, parameters, "PV"))

PRODUCT_FRA [['USD', np.float64(87.09029420688239)]]
PRODUCT_RFR_SWAP [['USD', np.float64(-2629.6795747881915)]]
PRODUCT_OVERNIGHT_INDEX_BASIS_SWAP [['USD', np.float64(8446.47247116697)]]

## 9. Product values

Use the public valuation API to display each product's PV.

In [18]:
products = {"FRA": fra, "RFR swap": swap, "Overnight basis swap": basis_swap}
pv_rows = [[name, qfCreateValueReport(model, product, parameters, "PV")[0][1]]
           for name, product in products.items()]
display(pd.DataFrame(pv_rows, columns=["Product", "PV"]))

                Product            PV
0                   FRA     87.090294
1              RFR swap -2,629.679575
2  Overnight basis swap  8,446.472471

## Results and validation

With the supplied synthetic inputs and value date **2026-01-02**, all values are in USD:

| Product / leg | PV |
|---|---:|
| FRA, receive fixed | 87.090294207 |
| RFR swap fixed leg | 38,534.539463150 |
| RFR swap floating leg | 41,164.219037938 |
| RFR swap, receive fixed | -2,629.679574788 |
| Basis swap SOFR plus spread leg | 42,163.002863421 |
| Basis swap Fed Funds leg | 33,716.530392254 |
| Basis swap, receive SOFR plus spread | 8,446.472471167 |

All 18 code cells ran from a fresh kernel with no errors, including the supplied formula and factory-equivalence assertions. The separate `tests/test_interest_rate_products.py` suite passes all 13 tests: independent flat-curve formulas; separate projection/funding rates; spread placement; fixed versus floating day counts; pay/receive signs; repeated valuation; same-day and expired cashflows; payment lag; schedule frequencies; convention mappings; serialization; and signed report reconciliation.

Validation environment: Python 3.13.6, NumPy 2.3.2, pandas 2.3.1, QuantLib 1.41. The starter's pinned NumPy version targets Python 3.11, so the local validation used the available compatible Python 3.13 packages. Run under the recommended Python 3.11 environment for course reproducibility. No starter inputs were changed.